steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/repo/subscription', '.' ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-east1-docker.pkg.dev/$PROJECT_ID/repo/subscription']

options:
  logging: CLOUD_LOGGING_ONLY