version: '3.9'

services:
  # subscription_db:
  #   image: postgres:15-bullseye
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_PORT: 5432
  #   ports:
  #     - 6200:5432
  #   networks:
  #     - subscription_net
  #   deploy:  
  #     resources:
  #       limits:
  #         cpus: '0.2'
  #         memory: 300M

  subscription:
    build:
      context: .
      dockerfile: Dockerfile.develop
    volumes:
      - .:/usr/src/app
    ports:
      - 6450:80
    networks:
      - subscription_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
    # depends_on:
    #   subscription_db:
    #     condition: service_started

networks:
  subscription_net:
    driver: bridge
    name: subscription_net