apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  labels:
    app: subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: my-app-image
          resources:
            limits:
              memory: "60Mi"
              cpu: "0.08"
            requests:
              memory: "60Mi"
              cpu: "0.08"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: "AUTH_HOST"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: AUTH_HOST
            - name: "AUTH_PATH_AUTH"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: AUTH_PATH_AUTH

            - name: "SUBSCRIPTION_DB_USER"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: SUBSCRIPTION_DB_USER
            - name: "SUBSCRIPTION_DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: SUBSCRIPTION_DB_HOST
            - name: "SUBSCRIPTION_DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: SUBSCRIPTION_DB_NAME
            - name: "SUBSCRIPTION_DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: SUBSCRIPTION_DB_PASSWORD
            - name: "SUBSCRIPTION_DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: appsecrets 
                  key: SUBSCRIPTION_DB_PORT

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: subscription-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 80
    type: HTTP
    requestPath: /subscription/ping